RackGetTime
rublen/RackGetTime pull request #1
Opened 2018-08-25 11:43 UTC by rublen

2018-08-26 09:54 UTC, psylone requested changes

2018-08-26 09:54 UTC, psylone commented on app.rb
> +    if @env['PATH_INFO'] == '/time' && @env['QUERY_STRING'][0..6] == 'format='
Используй объект класса `Rack::Request` для работы с параметрами.

2018-08-26 09:54 UTC, psylone commented on app.rb
> +    return [] if status == 404
У тебя везде происходит проветка статуса ответа, это несовсем удобно. Попробуй подойти с такой стороны что ты в каком-то одном месте проверяешь URL запроса и отвечаешь либо с каким-нибудь `time_response`, либо `not_found_response` (это отдельные методы которые займутся обработкой запроса и формированием ответа совместимого с Rack).

2018-08-26 09:54 UTC, psylone commented on app.rb
> +      formats.map do |f|
Смотри, у нас есть класс Rack-приложения и некоторая бизнес-логика по вычислению формата времени. Это стоит разделять. То есть бизнес-логику формата времени вынести в отдельный класс. При этом, данный класс ничего не должен знать о том кто и где будет его использовать. То есть он ничего не должен знать про Rack-приложение, в частности про статус ответа и другие аспекты HTTP. И мы должны иметь возможность использовать этот класс где захотим: в консоли, в Ruby-приложении, в Rails или Rack.

2018-08-26 09:54 UTC, psylone commented on app.rb
> +      formats.map do |f|
Получается такой независимый класс который отвечает за одну обязанность - форматирование времени.

2018-08-27 10:10 UTC, psylone requested changes

2018-08-27 10:10 UTC, psylone commented on app.rb
> +  def proper_url?
Это довольно эфемерное условие. По факту, нам нужно знать лишь есть ли обработчик для конкретного URL или нет.

2018-08-27 10:10 UTC, psylone commented on app.rb
> +    @request.path == '/time' && @request.query_string[0..6] == 'format='
Есть метод `params`, там можно по ключу посмотреть есть ли нужный параметр.

2018-08-27 10:10 UTC, psylone commented on app.rb
> +    [FormattedTime.new(Time.now, formats).applay_template('-') + "\n"]
По-моему, здесь лишняя _a_ в слове `applay` )

2018-08-27 10:10 UTC, psylone commented on app.rb
> +    [FormattedTime.new(Time.now, formats).applay_template('-') + "\n"]
Нет смысла передавать `Time.now` в качестве аргумента, мы можем взять это значение внутри класса `FormattedTime`.

2018-08-27 10:10 UTC, psylone commented on app.rb
>    end
Вот это как раз должно уйти в класс `FormattedTime`.

2018-08-27 10:10 UTC, psylone commented on app.rb
> +    if proper_url? && unknown_formats.empty?
Здесь лучше использовать `case`. Кроме того, логика проверки формата должна быть у класса `FormattedTime`.

Иными словами, здесь может быть нечто вроде этого:

```ruby
case @request.path
when '/time'
  time_response
when <...>_response
  <...>_response
else
  not_found_response
end
```

2018-08-27 13:38 UTC, rublen commented on app.rb
> +    @request.path == '/time' && @request.query_string[0..6] == 'format='
@request.params.keys.include? 'format'

2018-08-27 13:39 UTC, rublen commented on app.rb
> +    [FormattedTime.new(Time.now, formats).applay_template('-') + "\n"]
да)

2018-08-27 14:06 UTC, rublen commented on app.rb
> +    [FormattedTime.new(Time.now, formats).applay_template('-') + "\n"]
а вдруг FormattedTime будем использовать в другом приложении и нужно будет отформатировать не текущее время?

2018-08-28 17:36 UTC, psylone approved these changes

2018-08-28 17:36 UTC, psylone commented on app.rb
> +  attr_reader :request, :formatter
Тебе не нужны методы чтобы обращаться к инстанс-переменным внутри класса.

2019-03-13 11:57 UTC, merged